MSO_AUTO_SHAPE_TYPE_DICT = {
    1: {"name": "RECTANGLE", "description": "Rectangle"},
    2: {"name": "PARALLELOGRAM", "description": "Parallelogram"},
    3: {"name": "TRAPEZOID", "description": "Trapezoid"},
    4: {"name": "DIAMOND", "description": "Diamond"},
    5: {"name": "ROUNDED RECTANGLE", "description": "Rounded rectangle"},
    6: {"name": "OCTAGON", "description": "Octagon"},
    7: {"name": "ISOSCELES_TRIANGLE", "description": "Isosceles triangle"},
    8: {"name": "RIGHT_TRIANGLE", "description": "Right triangle"},
    9: {"name": "OVAL", "description": "Oval"},
    10: {"name": "HEXAGON", "description": "Hexagon"},
    11: {"name": "CROSS", "description": "Cross"},
    12: {"name": "REGULAR_PENTAGON", "description": "Pentagon"},
    13: {"name": "CAN", "description": "Can"},
    14: {"name": "CUBE", "description": "Cube"},
    15: {"name": "BEVEL", "description": "Bevel"},
    16: {"name": "FOLDED_CORNER", "description": "Folded corner"},
    17: {"name": "SMILEY_FACE", "description": "Smiley face"},
    18: {"name": "DONUT", "description": "Donut"},
    19: {"name": "NO_SYMBOL", "description": "The 'No' Symbol"},
    20: {"name": "BLOCK_ARC", "description": "Block arc"},
    21: {"name": "HEART", "description": "Heart"},
    22: {"name": "LIGHTNING_BOLT", "description": "Lightning bolt"},
    23: {"name": "SUN", "description": "Sun"},
    24: {"name": "MOON", "description": "Moon"},
    25: {"name": "ARC", "description": "Arc"},
    26: {"name": "DOUBLE_BRACKET", "description": "Double bracket"},
    27: {"name": "DOUBLE_BRACE", "description": "Double brace"},
    28: {"name": "PLAQUE", "description": "Plaque"},
    29: {"name": "LEFT_BRACKET", "description": "Left bracket"},
    30: {"name": "RIGHT_BRACKET", "description": "Right bracket"},
    31: {"name": "LEFT_BRACE", "description": "Left brace"},
    32: {"name": "RIGHT_BRACE", "description": "Right brace"},
    33: {"name": "RIGHT_ARROW", "description": "Block arrow that points right"},
    34: {"name": "LEFT_ARROW", "description": "Block arrow that points left"},
    35: {"name": "UP_ARROW", "description": "Block arrow that points up"},
    36: {"name": "DOWN_ARROW", "description": "Block arrow that points down"},
    37: {"name": "LEFT_RIGHT_ARROW", "description": "Block arrow with arrowheads that point both left and right"},
    38: {"name": "UP_DOWN_ARROW", "description": "Block arrow that points up and down"},
    39: {"name": "QUAD_ARROW", "description": "Block arrows that point up, down left and right"},
    40: {"name": "LEFT_RIGHT_UP_ARROW", "description": "Block arrow with arrowheads that point left right and up"},
    41: {"name": "BENT_ARROW", "description": "Block arrow that follows a curved 90-degree angle"},
    42: {"name": "U_TURN_ARROW", "description": "Block arrow forming a U shape"},
    43: {"name": "LEFT_UP_ARROW", "description": "Block arrow with arrowheads that point left and up"},
    44: {"name": "BENT_UP_ARROW",
         "description": "Block arrow that follows a sharp 90-degree angle. Points up by" "default"},
    45: {"name": "CURVED RIGHT_ARROW", "description": "Block arrow that curves right"},
    46: {"name": "CURVED_LEFT_ARROW", "description": "Block arrow that curves left"},
    47: {"name": "CURVED_UP_ARROW", "description": "Block arrow that curves up"},
    48: {"name": "CURVED DOWN_ARROW", "description": "Block arrow that curves down"},
    49: {"name": "STRIPED_RIGHT_ARROW", "description": "Block arrow that points right with stripes at the tail"},
    50: {"name": "NOTCHED_RIGHT_ARROW", "description": "Notched block arrow that points right"},
    51: {"name": "PENTAGON", "description": "Pentagon"},
    52: {"name": "CHEVRON", "description": "Chevron"},
    53: {"name": "RIGHT_ARROW_CALLOUT", "description": "Callout with arrow that points right"},
    54: {"name": "LEFT_ARROW_CALLOUT", "description": "Callout with arrow that points left"},
    55: {"name": "UP_ARROW_CALLOUT", "description": "Callout with arrow that points up"},
    56: {"name": "DOWN_ARROW_CALLOUT", "description": "Callout with arrow that points down"},
    57: {"name": "LEFT_RIGHT_ARROW_CALLOUT", "description": "Callout with arrowheads that point both left and right"},
    58: {"name": "UP_DOWN_ARROW_CALLOUT", "description": "Callout with arrows that point up and down"},
    59: {"name": "QUAD_ARROW_CALLOUT", "description": "Callout with arrows that point up, down left and right"},
    60: {"name": "CIRCULAR_ARROW", "description": "Block arrow that follows a curved 180-degree angle"},
    61: {"name": "FLOWCHART_PROCESS", "description": "Process flowchart symbol"},
    62: {"name": "FLOWCHART_ALTERNATE_PROCESS", "description": "Alternate process flowchart symbol"},
    63: {"name": "FLOWCHART DECISION", "description": "Decision flowchart symbol"},
    64: {"name": "FLOWCHART DATA", "description": "Data flowchart symbol"},
    65: {"name": "FLOWCHART PREDEFINED_PROCESS", "description": "Predefined process flowchart symbol"},
    66: {"name": "FLOWCHART_INTERNAL_STORAGE", "description": "Internal storage flowchart symbol"},
    67: {"name": "FLOWCHART_DOCUMENT", "description": "Document flowchart symbol"},
    68: {"name": "FLOWCHART_MULTIDOCUMENT", "description": "Multi-document flowchart symbol"},
    69: {"name": "FLOWCHART TERMINATOR", "description": "Terminator flowchart symbol"},
    70: {"name": "FLOWCHART PREPARATION", "description": "Preparation flowchart symbol"},
    71: {"name": "FLOWCHART_MANUAL_INPUT", "description": "Manual input flowchart symbol"},
    72: {"name": "FLOWCHART_MANUAL_OPERATION", "description": "Manual operation flowchart symbol"},
    73: {"name": "FLOWCHART CONNECTOR", "description": "Connector flowchart symbol"},
    74: {"name": "FLOWCHART_OFFPAGE_CONNECTOR", "description": "Off-page connector flowchart symbol"},
    75: {"name": "FLOWCHART CARD", "description": "Card flowchart symbol"},
    76: {"name": "FLOWCHART_PUNCHED_TAPE", "description": "Punched tape flowchart symbol"},
    77: {"name": "FLOWCHART_SUMMING JUNCTION", "description": "Summing junction flowchart symbol"},
    78: {"name": "FLOWCHART_OR", "description": "Or flowchart symbol"},
    79: {"name": "FLOWCHART COLLATE", "description": "Collate flowchart symbol"},
    80: {"name": "FLOWCHART_SORT", "description": "Sort flowchart symbol"},
    81: {"name": "FLOWCHART_EXTRACT", "description": "Extract flowchart symbol"},
    82: {"name": "FLOWCHART_MERGE", "description": "Merge flowchart symbol"},
    83: {"name": "FLOWCHART_STORED_DATA", "description": "Stored data flowchart symbol"},
    84: {"name": "FLOWCHART_DELAY", "description": "Delay flowchart symbol"},
    85: {"name": "FLOWCHART SEQUENTIAL_ACCESS_STORAGE", "description": "Sequential access storage flowchart symbol"},
    86: {"name": "FLOWCHART MAGNETIC_DISK", "description": "Magnetic disk flowchart symbol"},
    87: {"name": "FLOWCHART DIRECT_ACCESS_STORAGE", "description": "Direct access storage flowchart symbol"},
    88: {"name": "FLOWCHART DISPLAY", "description": "Display flowchart symbol"},
    89: {"name": "EXPLOSION1", "description": "Explosion"},
    90: {"name": "EXPLOSION2", "description": "Explosion"},
    91: {"name": "STAR_4_POINT", "description": "4-point star"},
    92: {"name": "STAR_5_POINT", "description": "5-point star"},
    93: {"name": "STAR_8_POINT", "description": "8-point star"},
    94: {"name": "STAR_16_POINT", "description": "16-point star"},
    95: {"name": "STAR_24_POINT", "description": "24-point star"},
    96: {"name": "STAR_32_POINT", "description": "32-point star"},
    97: {"name": "UP_RIBBON", "description": "Ribbon banner with center area above ribbon ends"},
    98: {"name": "DOWN_RIBBON", "description": "Ribbon banner with center area below ribbon ends"},
    99: {"name": "CURVED_UP_RIBBON", "description": "Ribbon banner that curves up"},
    100: {"name": "CURVED DOWN_RIBBON", "description": "Ribbon banner that curves down"},
    101: {"name": "VERTICAL_SCROLL", "description": "Vertical scroll"},
    102: {"name": "HORIZONTAL_SCROLL", "description": "Horizontal scroll"},
    103: {"name": "WAVE", "description": "Wave"},
    104: {"name": "DOUBLE_WAVE", "description": "Double wave"},
    105: {"name": "RECTANGULAR CALLOUT", "description": "Rectangular callout"},
    106: {"name": "ROUNDED_RECTANGULAR_CALLOUT", "description": "Rounded rectangle-shaped callout"},
    107: {"name": "OVAL CALLOUT", "description": "Oval-shaped callout"},
    108: {"name": "CLOUD_CALLOUT", "description": "Cloud callout"},
    109: {"name": "LINE_CALLOUT_1", "description": "Callout with border and horizontal callout line"},
    110: {"name": "LINE_CALLOUT_2", "description": "Callout with diagonal straight line"},
    111: {"name": "LINE_CALLOUT 3", "description": "Callout with angled line"},
    112: {"name": "LINE_CALLOUT 4", "description": "Callout with callout line segments forming a U-shape."},
    113: {"name": "LINE_CALLOUT_1_ACCENT BAR", "description": "Callout with vertical accent bar"},
    114: {"name": "LINE_CALLOUT_2_ACCENT BAR", "description": "Callout with diagonal callout line and accent bar"},
    115: {"name": "LINE_CALLOUT 3 ACCENT BAR", "description": "Callout with angled callout line and accent bar"},
    116: {"name": "LINE_CALLOUT_4_ACCENT_BAR",
          "description": "Callout with accent bar and callout line segments forming a U-s" "hape."},
    117: {"name": "LINE_CALLOUT_1_NO_BORDER", "description": "Callout with horizontal line"},
    118: {"name": "LINE_CALLOUT_2_NO_BORDER", "description": "Callout with no border and diagonal callout line"},
    119: {"name": "LINE_CALLOUT_3_NO_BORDER", "description": "Callout with no border and angled callout line"},
    120: {"name": "LINE_CALLOUT_4_NO_BORDER",
          "description": "Callout with no border and callout line segments forming a U-sh" "ape."},
    121: {"name": "LINE_CALLOUT_1_BORDER_AND_ACCENT_BAR",
          "description": "Callout with border and vertical accent bar"},
    122: {"name": "LINE_CALLOUT_2_BORDER_AND_ACCENT_BAR",
          "description": "Callout with border diagonal straight line and accent bar"},
    123: {"name": "LINE_CALLOUT_3_BORDER_AND_ACCENT_BAR",
          "description": "Callout with border angled callout line and accent bar"},
    124: {"name": "LINE_CALLOUT_4_BORDER_AND_ACCENT BAR",
          "description": "Callout with border accent bar and callout line segments form" "ing a U-shape."},
    125: {"name": "ACTION_BUTTON_CUSTOM",
          "description": "Button with no default picture or text. Supports mouse-click an" "d mouse-over actions"},
    126: {"name": "ACTION_BUTTON_HOME", "description": "Home button. Supports mouse-click and mouse-over actions"},
    127: {"name": "ACTION_BUTTON_HELP", "description": "Help button. Supports mouse-click and mouse-over actions"},
    128: {"name": "ACTION_BUTTON_INFORMATION",
          "description": "Information button. Supports mouse-click and mouse-over actions"},
    129: {"name": "ACTION_BUTTON_BACK_OR_PREVIOUS",
          "description": "Back or Previous button. Supports" "mouse-click and mouse-over actions"},
    130: {"name": "ACTION_BUTTON_FORWARD_OR_NEXT",
          "description": "Forward or Next button. Supports mouse-click and mouse-over actions"},
    131: {"name": "ACTION_BUTTON_BEGINNING",
          "description": "Beginning button. Supports mouse-click and mouse-over actions"},
    132: {"name": "ACTION_BUTTON_END", "description": "End button. Supports mouse-click and mouse-over actions"},
    133: {"name": "ACTION_BUTTON_RETURN", "description": "Return button. Supports mouse-click and mouse-over actions"},
    134: {"name": "ACTION_BUTTON_DOCUMENT",
          "description": "Document button. Supports mouse-click and mouse-over actions"},
    135: {"name": "ACTION_BUTTON_SOUND", "description": "Sound button. Supports mouse-click and mouse-over actions"},
    136: {"name": "ACTION_BUTTON_MOVIE", "description": "Movie button. Supports mouse-click and mouse-over actions"},
    137: {"name": "BALLOON", "description": "Rounded Rectangular Callout"},
    138: {"name": "NA", "description": "Not valid"},
    139: {"name": "FLOWCHART OFFLINE_STORAGE", "description": "Offline Storage"},
    140: {"name": "LEFT_RIGHT_RIBBON", "description": "Left Right Ribbon"},
    141: {"name": "DIAGONAL_STRIPE", "description": "Diagonal Stripe"},
    142: {"name": "PIE", "description": "Pie"},
    143: {"name": "NON_ISOSCELES_TRAPEZOID", "description": "Non-isosceles Trapezoid"},
    144: {"name": "DECAGON", "description": "Decagon"},
    145: {"name": "HEPTAGON", "description": "Heptagon"},
    146: {"name": "DODECAGON", "description": "Dodecagon"},
    147: {"name": "STAR_6_POINT", "description": "6-Point Star"},
    148: {"name": "STAR_7_POINT", "description": "7-Point Star"},
    149: {"name": "STAR_10_POINT", "description": "10-Point Star"},
    150: {"name": "STAR_12_POINT", "description": "12-Point Star"},
    151: {"name": "ROUND_1_RECTANGLE", "description": "Round Single Corner Rectangle"},
    152: {"name": "ROUND_2_SAME_RECTANGLE", "description": "Round Same Side Corner Rectangle"},
    153: {"name": "ROUND_2_DIAG_RECTANGLE", "description": "Round Diagonal Corner Rectangle"},
    154: {"name": "SNIP_ROUND_RECTANGLE", "description": "Snip and Round Single Corner Rectangle"},
    155: {"name": "SNIP_1_RECTANGLE", "description": "Snip Single Corner Rectangle"},
    156: {"name": "SNIP_2_SAME_RECTANGLE", "description": "Snip Same Side Corner Rectangle"},
    157: {"name": "SNIP_2_DIAG RECTANGLE", "description": "Snip Diagonal Corner Rectangle"},
    158: {"name": "FRAME", "description": "Frame"},
    159: {"name": "HALF_FRAME", "description": "Half Frame"},
    160: {"name": "TEAR", "description": "Teardrop"},
    161: {"name": "CHORD", "description": "Geometric chord shape"},
    162: {"name": "CORNER", "description": "Corner"},
    163: {"name": "MATH_PLUS", "description": "Plus"},
    164: {"name": "MATH_MINUS", "description": "Minus"},
    165: {"name": "MATH_MULTIPLY", "description": "Multiply"},
    166: {"name": "MATH_DIVIDE", "description": "Division"},
    167: {"name": "MATH_EQUAL", "description": "Equal"},
    168: {"name": "MATH_NOT_EQUAL", "description": "Not Equal"},
    169: {"name": "CORNER_TABS", "description": "Corner Tabs"},
    170: {"name": "SQUARE_TABS", "description": "Square Tabs"},
    171: {"name": "PLAQUE_TABS", "description": "Plaque Tabs"},
    172: {"name": "GEAR_6", "description": "Gear 6"},
    173: {"name": "GEAR_9", "description": "Gear 9"},
    174: {"name": "FUNNEL", "description": "Funnel"},
    175: {"name": "PIE_WEDGE", "description": "Pie"},
    176: {"name": "LEFT_CIRCULAR_ARROW", "description": "Left Circular Arrow"},
    177: {"name": "LEFT_RIGHT_CIRCULAR_ARROW", "description": "Left Right Circular Arrow"},
    178: {"name": "SWOOSH_ARROW", "description": "Swoosh Arrow"},
    179: {"name": "CLOUD", "description": "Cloud"},
    180: {"name": "CHART_X", "description": "Chart X"},
    181: {"name": "CHART_STAR", "description": "Chart Star"},
    182: {"name": "CHART_PLUS", "description": "Chart Plus"},
    183: {"name": "LINE_INVERSE", "description": "Straight Connector"}}

MSO_SHAPE_TYPE_DICT = {
    -2: {"name": "MIXED", "description": "Mixed shape types"},
    1: {"name": "AUTO_SHAPE", "description": "AutoShape"},
    2: {"name": "CALLOUT", "description": "Callout shape"},
    3: {"name": "CHART", "description": "Chart, eg pie chart, bar chart"},
    4: {"name": "COMMENT", "description": "Comment"},
    5: {"name": "FREEFORM", "description": "Freeform"},
    6: {"name": "GROUP", "description": "Group shape"},
    7: {"name": "EMBEDDED_OLE_OBJECT", "description": "Embedded OLE object"},
    8: {"name": "FORM_CONTROL", "description": "Form control"},
    9: {"name": "LINE", "description": "Line"},
    10: {"name": "LINKED_OLE_OBJECT", "description": "Linked OLE object"},
    11: {"name": "LINKED PICTURE", "description": "Linked picture"},
    12: {"name": "OLE_CONTROL_OBJECT", "description": "OLE control object"},
    13: {"name": "PICTURE", "description": "Picture"},
    14: {"name": "PLACEHOLDER", "description": "Placeholder"},
    15: {"name": "TEXT_EFFECT", "description": "Text effect"},
    16: {"name": "MEDIA", "description": "Media"},
    17: {"name": "TEXT_BOX", "description": "Text box"},
    18: {"name": "SCRIPT_ANCHOR", "description": "Script anchor"},
    19: {"name": "TABLE", "description": "Table"},
    20: {"name": "CANVAS", "description": "Drawing canvas"},
    21: {"name": "DIAGRAM", "description": "Diagram"},
    22: {"name": "INK", "description": "Ink"},
    23: {"name": "INK_COMMENT", "description": "Ink Comment"},
    24: {"name": "IGX_GRAPHIC", "description": "SmartArt graphic"},
    25: {"name": "NA", "description": "Not Valid"},
    26: {"name": "WEB_VIDEO", "description": "Web video"},
}
